# fly.toml app configuration file generated for dchp3 on 2023-05-23T15:35:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dchp3"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  cmd = ["start-fly.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[env]
  IMAGE_BUCKET_PREFIX = "https://pub-4a7db9194f8547b3bb7041d55b194d34.r2.dev"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"
