export enum EntryEditorFormActionEnum {
  UPDATE_ENTRY = "UpdateEntry",
  UPDATE_MEANING = "UpdateMeaning",
  ADD_MEANING = "AddMeaning",
  DELETE_MEANING = "DeleteMeaning",
  ADD_QUOTATIONS = "Quotation",
  DELETE_QUOTATION = "DeleteQuotation",
  ADD_SEE_ALSO = "SeeAlso",
  DELETE_SEE_ALSO = "DeleteSeeAlso",
  DEFINITION_FIST_NOTE = "DefintionFistNote",
  ADD_DEFINITION_FIST_NOTE = "AddDefintionFistNote",
  EDITING_TOOLS = "EditingTools",
  EDITING_STATUS = "EditingStatus",
  COMMENT = "Comment",
  DELETE_IMAGE = "DeleteImage",
  ADD_IMAGE = "AddImage",
  EDIT_IMAGE = "EditImage",
  ADD_REFERENCE = "AddReference",
  DELETE_REFERENCE = "DeleteReference",
}
