export enum EntryEditorFormActionEnum {
  DELETE_ENTRY = "Delete entry",
  UPDATE_ENTRY = "Update entry",
  UPDATE_MEANING = "Update meaning",
  ADD_MEANING = "Add meaning",
  DELETE_MEANING = "Delete meaning",
  ADD_QUOTATIONS = "Add citation",
  DELETE_QUOTATION = "Delete citation",
  ADD_SEE_ALSO = "Add see also",
  DELETE_SEE_ALSO = "Delete see also",
  DEFINITION_FIST_NOTE = "Update or delete definition fist note",
  ADD_DEFINITION_FIST_NOTE = "Add definition fist note",
  EDITING_TOOLS = "Toggle public visibility",
  EDITING_STATUS = "Change editing status",
  COMMENT = "Comment",
  DELETE_IMAGE = "Delete image",
  ADD_IMAGE = "Add image",
  EDIT_IMAGE = "Edit image",
  ADD_REFERENCE = "Add reference",
  DELETE_REFERENCE = "Delete reference",
}
