export enum attributeEnum {
  ENTRY = "Entry",
  MEANING = "Meaning",
  HEADWORD = "Headword",
  SPELLING_VARIANT = "SpellingVariant",
  ETYMOLOGY = "Etymology",
  LABELS = "Labels",
  FIST_NOTE = "FistNote",
  DAGGER = "Dagger",
  ADD_MEANING = "AddMeaning",
  DELETE_MEANING = "DeleteMeaning",
  QUOTATION = "Quotation",
  DELETE_QUOTATION = "DeleteQuotation",
  // Note: MEANING_HEADER does not directly correspond to any individual entry field
  // TODO: Is there a cleaner way to handle this situation?
  MEANING_HEADER = "MeaningHeader",
  SEE_ALSO = "SeeAlso",
  DELETE_SEE_ALSO = "DeleteSeeAlso",
  CANADIANISM = "Canadianism",
  DEFINITION = "Definition",
  DEFINITION_FIST_NOTE = "DefintionFistNote",
  ADD_DEFINITION_FIST_NOTE = "AddDefintionFistNote",
  EDITING_TOOLS = "EditingTools",
  EDITING_STATUS = "EditingStatus",
  COMMENT = "Comment",
}
